### ISSUE TITLE
The named parameter 'dropdownSearchDecoration' isn't defined

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [salim-lachdhaf/searchable_dropdown#431]
**Describe the bug**
I have the latest version of `dropdown_search`, v5.0.2 added to my project.

In the examples shown in the README, they show a property named `dropdownSearchDecoration. But trying to call that method in the latest version throws the following error.

> The named parameter 'dropdownSearchDecoration' isn't defined

**pubspec.yaml**
```yaml
name: dropdownsearch_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dropdown_search: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

```dart
Widget dropdown() {
    return DropdownSearch<String>(
      popupProps: PopupProps.menu(
        showSelectedItems: true,
        disabledItemFn: (String s) => s.startsWith('I'),
      ),
      items: const ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
      dropdownSearchDecoration: const InputDecoration(
        labelText: "Menu mode",
        hintText: "country in menu mode",
      ),
      onChanged: print,
      selectedItem: "Brazil",
    );
  }
```
<img width="918" alt="Screenshot 2022-06-09 at 7 04 29 PM" src="https://user-images.githubusercontent.com/2551877/172860017-49cc462f-bf75-4987-9185-28d7002923f4.png">
