### ISSUE TITLE
Equavalent of 'onDismiss' in Dialog Mode

### ISSUE THREAD

**Issue by alandotic** [salim-lachdhaf/searchable_dropdown#97]
Hi, i would want to have an event when the dropdown got dismissed, how can i achieve it in this library? I tried to use onChange but it only get called when the selected value changed.

For example, i would want to show the validation message when user open and close the dropdown( like tapping on the grey area of the popup).

The behavior i wanted to achieve:

User tap the DropdownSearch, User close the DropdownSearch (tapping dark gray background), validation message will be shown

**Comment by vasilich6107** [comment]
Try

```
  dropdown_search:
    git:
      url: https://github.com/artflutter/searchable_dropdown.git
      ref: feature/onpopupdismiss-callback
```

And tell us if it fits your needs
